### ISSUE TITLE
I've seen other closed issues about this, but I'm stil having it.

### ISSUE THREAD

**Issue by Ostarr** [jaredlll08/Clumps#80]
I like this mod, optimisation is very much a needed thing for Minecraft, however, while using this mod I noticed the mending enchantment was repairing my tools incredibly slowly. I then disabled the mod and it was fine.
This issue looks like it's being casued by the enchantment only repairing your tools for every xp orb you collect, and since they're all clumped into one orb, you only get one set amount of repair.
You should be able to fix this by changing the mending enchant to work based on how much xp is in the orb, rather than the amount of orbs being collected.
While mending is moslty for vanilla use, in lighter modpacks and even with popular mods like Tinker's Construct I can see this being an issue. Please fix this as I'd like to continue using this mod.

**Comment by jaredlll08** [comment]
MC version?
Clumps version?

**Comment by Ostarr** [comment]
Minecraft 1.16.5
Clumps-6.0.0.25
Forge 36.2.0

**Comment by jaredlll08** [comment]
Here is a side by side comparison of Clumps (on the left) and Vanilla (on the right). 

https://www.youtube.com/watch?v=_0Bo2yb63Eo

Here are the stats from that video.
```yml
Start:
  Clumps:
    offhand: 561
    mainhand: 561
    helmet: 63
    chestplate: 228
    leggings: 195
    boots: 129

  Vanilla:
    offhand: 561
    mainhand: 561
    helmet: 63
    chestplate: 228
    leggings: 195
    boots: 129

End:
  Clumps:
    offhand: 679
    mainhand: 713
    helmet: 227
    chestplate: 318
    leggings: 381
    boots: 331

  Vanilla:
    offhand: 653
    mainhand: 649
    helmet: 215
    chestplate: 358
    leggings: 399
    boots: 305

Differences:
  Clumps:
    offhand: 118
    mainhand: 152
    helmet: 164
    chestplate: 90
    leggings: 186
    boots: 202
    total_mending_done: 912

  Vanilla:
    offhand: 92
    mainhand: 88
    helmet: 164
    chestplate: 130
    leggings: 204
    boots: 176
    total_mending_done: 854
```

The way that vanilla converts experience to damage is by just doubling it, so `1` experience will mend 2 damage.

So if we take our totals of 912 and 854 for Clumps and Vanilla respectively, we can see that the Clumps orbs had a value of `456` and the Vanilla orbs had a combined value of `427`.

From here we can calculate the average experienced spawned for each test.
The average for the Clumps test is 7.125 (456/64).
The average for the Vanilla test is 6.671875 (427/64).

As stated on the Minecraft wiki [here](https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting#Usage), the bottle o' enchanting on average spawns orbs with an average value of `7`.
Which is more or less what both test showed (although the Clumps test was a bit higher, I'm sure if one had to do more tests they would see that it is the same).

I don't know what to tell you, but the logic emulates vanilla's mending nearly perfectly (if not perfect).
